# Generated by Django 4.2.11 on 2024-05-25 16:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('autores_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('genero_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('libros_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(max_length=300)),
                ('año_publicacion', models.IntegerField()),
                ('portada_url', models.URLField()),
                ('autores_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='resenas_app.autores')),
                ('genero_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='resenas_app.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuarios_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('tipo_usuario', models.CharField(choices=[('lector', 'Lector'), ('administrador', 'Administrador')])),
            ],
        ),
        migrations.CreateModel(
            name='Reseñas',
            fields=[
                ('reseña_id', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField()),
                ('comentario', models.TextField()),
                ('fecha_reseña', models.DateTimeField(default=django.utils.timezone.now)),
                ('libro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='resenas_app.libros')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='resenas_app.usuarios')),
            ],
        ),
    ]
