# Generated by Django 4.2.11 on 2024-05-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resenas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='tipo_usuario',
            field=models.CharField(default='Lector'),
        ),
    ]
