# Generated by Django 4.2.11 on 2024-05-26 16:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resenas_app', '0004_alter_reseñas_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseñas',
            name='comentario',
            field=models.TextField(max_length=500),
        ),
        migrations.CreateModel(
            name='ComentarioReseña',
            fields=[
                ('comentario_id', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField(max_length=300)),
                ('fecha_comentario', models.DateTimeField(default=django.utils.timezone.now)),
                ('reseña', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='resenas_app.reseñas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='resenas_app.usuarios')),
            ],
        ),
    ]
