# Generated by Django 4.2.11 on 2024-05-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resenas_app', '0005_alter_reseñas_comentario_comentarioreseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
