# Generated by Django 4.2.11 on 2024-05-27 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resenas_app', '0007_usuarios_groups_usuarios_is_active_usuarios_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
