# Generated by Django 4.2.11 on 2024-05-27 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resenas_app', '0008_alter_usuarios_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
