# Generated by Django 4.2.11 on 2024-05-27 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resenas_app', '0010_alter_usuarios_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguirAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seguimiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to='resenas_app.autores')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
